### ISSUE TITLE
Issue with useNewUrlParser and useUnifiedTopology as they are depreciated 

### ISSUE THREAD

**Issue by coderight1** [rachit-bhatt/ResumeHub#2]
`require('dotenv').config();
const mongoose = require('mongoose');
const app = require('./app');

const PORT = process.env.PORT || 5000;

mongoose.connect(process.env.MONGO_URI, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
}).then(() => {
  console.log('Connected to MongoDB');
  app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
  });
}).catch(err => {
  console.error('Connection error', err.message);
});`

**Comment by rachit-bhatt** [comment]
Thank you very much for your precious observation. We will deal with this issue in our development process if it is a problematic in priority and will leave it in the future after releasing the first working version of the project.
